### PR TITLE
reduced image height

### PR DESCRIPTION
**Pull request by elhaw**
### Description 

- reduced the image height to reduce the ga between the title and description

### CODE REVIEW

**Comment by AbdoMgdy** [comment]
this makes the image very small. try to change the structure by putting the heading and the description in a flex-col and the image besides them .

note: the current structure the heading and the image are in the same div.

**Review by AbdoMgdy — CHANGES_REQUESTED** [review]
this makes the image very small. try to change the structure by putting the heading and the description in a flex-col and the image besides them .

note: the current structure the heading and the image are in the same div.

**Review by MAlngaawy — APPROVED** [review]
LGTM

**Comment by elhaw** [comment]
The image has been removed from the new design

**Pull request closed without merging**
